apiVersion: v2
name: wasp-service-template
appVersion: '0.0.6'
description: A Helm chart for wasp-service-template
version: '0.0.6'
type: application
maintainers:
  - name: digicatapult
    email: opensource@digicatapult.org.uk
    url: www.digicatapult.org.uk
